server:
  port: 8080

  error:
    include-message: never
    include-stacktrace: never

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

cors:
  allowed-origins:
    - https://templebar.ru
    - https://admin.templebar.ru

cookie:
  secure: true

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
