spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

server:
  servlet:
    session:
      persistent: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
