spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

jwt:
  secret: ${JWT_SECRET}

cookie:
  secure: false

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
