server:
  port: 8080

  error:
    include-message: never
    include-stacktrace: never

cors:
  allowed-origins:
    - https://templebar.ru
    - https://admin.templebar.ru

storage:
  upload-directory: ${STORAGE_UPLOAD_DIRECTORY}

cookie:
  secure: true

logging:
  level:
    root: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
